// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_9vHV9_LOQjMe6dvtx1kloZdysQuLYvk',
    appId: '1:457026938747:web:d635182fe7549fafa93fde',
    messagingSenderId: '457026938747',
    projectId: 'mediconnect-867a8',
    authDomain: 'mediconnect-867a8.firebaseapp.com',
    storageBucket: 'mediconnect-867a8.firebasestorage.app',
    measurementId: 'G-ZD65BGDYNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2VVpHTXWyMlyvRLWsJEdXLoPbKZmpIIE',
    appId: '1:457026938747:android:3d33afdd06df062da93fde',
    messagingSenderId: '457026938747',
    projectId: 'mediconnect-867a8',
    storageBucket: 'mediconnect-867a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvjhx7NF6Soqb2C1d4fjQTxcmsGAe-kf8',
    appId: '1:457026938747:ios:b263d9bd1dd70604a93fde',
    messagingSenderId: '457026938747',
    projectId: 'mediconnect-867a8',
    storageBucket: 'mediconnect-867a8.firebasestorage.app',
    iosBundleId: 'com.mediconnect.mediconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvjhx7NF6Soqb2C1d4fjQTxcmsGAe-kf8',
    appId: '1:457026938747:ios:b263d9bd1dd70604a93fde',
    messagingSenderId: '457026938747',
    projectId: 'mediconnect-867a8',
    storageBucket: 'mediconnect-867a8.firebasestorage.app',
    iosBundleId: 'com.mediconnect.mediconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_9vHV9_LOQjMe6dvtx1kloZdysQuLYvk',
    appId: '1:457026938747:web:4b2ea92ea844afcca93fde',
    messagingSenderId: '457026938747',
    projectId: 'mediconnect-867a8',
    authDomain: 'mediconnect-867a8.firebaseapp.com',
    storageBucket: 'mediconnect-867a8.firebasestorage.app',
    measurementId: 'G-S85CFV4VGK',
  );
}
